### PR TITLE
Added Japanese and Ryukyuan translations

### PR DESCRIPTION
**Pull request by kuragehimekurara1**
Added Japanese and Ryukyuan translations

### CODE REVIEW

**Comment by kuragehimekurara1** [comment]
https://en.wikipedia.org/wiki/Ryukyuan_languages?wprov=sfti1
If you don't understand Ryukyuan languages, please see this Wikipedia page.

**Comment by xfangfang** [comment]
Thank you very much for your contribution to this project. 

There are two things that need to be modified
1. version.json does not need to be provided.
2. The `Nintendo Switch` itself only supports one Japanese language. You need to name the folder to `ja`. However, you can keep the other one, because I may make an application setting later to manually switch the language.

205573585-4d27338a-3503-493a-9d68-3f6d2979a81b

**Comment by kuragehimekurara1** [comment]
Should I delete version.json for both Ryukyuan languages ​​and Japanese?

**Comment by xfangfang** [comment]
> Should I delete version.json for both Ryukyuan languages ​​and Japanese?

Yes

**Comment by kuragehimekurara1** [comment]
It has changed!👍

**Comment by xfangfang** [comment]
> It has changed!👍

Thanks, I will merge it after github actions jobs are done.

**Pull request merged**
